apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-sak
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /k9/sak/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
    # nais will try failureThreshold times before giving up and restarting the Pod
    # Defaults to 3
  readiness:
    path: /k9/sak/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /k9/sak/internal/metrics/prometheus
  resources:
    limits:
      cpu: "500m"
      memory: "2048Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"
  ingresses:
    - "https://k9-sak.nais.preprod.local/"
  kafka:
    pool: "nav-dev"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvk9sak
      - mountPath: /var/run/secrets/nais.io/ldap
        kvPath: /serviceuser/data/dev/srvssolinux
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/k9-sak/k9saksbehandling
  sidecar: true
  env:
    - name: TZ
      value: "Europe/Oslo"
    - name: APP_NAME
      value: "K9SAK"

    - name: DEFAULTDS_USERNAME
      value: k9-sak
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/k9-sak

    # Appdynamics
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: NON-PROD

    # Integrasjoner (Kafka)
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse
    - name: KAFKA_DOKUMENTBESTILLING_TOPIC
      value: privat-k9-dokumenthendelse
    - name: KAFKA_INFOTRYGDFEED_TOPIC
      value: privat-k9-infotrygdFeedHendelse
    - name: KAFKA_FATTEVEDTAK_TOPIC
      value: privat-familie-vedtakFattet-v1-q1
    - name: KAFKA_VEDTAKHENDELSE_TOPIC
      value: privat-k9-vedtakhendelse
    - name: KAFKA_STONADSTATISTIKK_TOPIC
      value: k9saksbehandling.aapen-k9-stonadstatistikk-v1
    - name: KAFKA_BRUKERDIALOGINNSYN_TOPIC
      value: dusseldorf.privat-k9-sak-innsyn-v1
    - name: KAFKA_PRODUKSJONSSTYRING_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-sak-v1
    - name: KAFKA_K9_RAPID_TOPIC
      value: omsorgspenger.k9-rapid-v2

    # Baseurl
    - name: SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.preprod.local
    - name: BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443

    # Loadbalancerconfig
    - name: LOADBALANCER_URL
      value: https://app-q1.adeo.no

    # LDAP
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local
    - name: LDAP_BASEDN
      value: "dc=preprod,dc=local"
    - name: LDAP_DOMAIN
      value: "PREPROD.LOCAL"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=preprod,dc=local"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=preprod,dc=local"

    # PDL
    - name: PDL_TEMA
      value: OMS

    # Restservice Generelle
    - name: INFOTRYGD_HENDELSER_API_URL
      value: http://infotrygd-hendelse-api.default/infotrygd/hendelser
    - name: FPABAKUS_URL
      value: http://fpabakus.teamforeldrepenger/fpabakus
    - name: FTKALKULUS_URL
      value: http://ftkalkulus.k9saksbehandling/ftkalkulus
    - name: ABAKUS_CALLBACK_URL
      value: http://k9-sak.k9saksbehandling/k9/sak/api/registerdata/iay/callback
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.default/application/authorize
    - name: K9_OPPDRAG_PROXY_URL
      value: https://app-q1.adeo.no/k9/oppdrag/api
    - name: ARBEIDSFORDELING_RS_URL
      value: https://app-q1.adeo.no/norg2/api/v1/arbeidsfordeling/enheter
    - name: OPPGAVE_RS_URI
      value: https://oppgave-q1.nais.preprod.local/api/v1/oppgaver
    - name: MEDL2_RS_URL
      value: https://medlemskap-medl-api.dev.intern.nav.no/api/v1/medlemskapsunntak
    - name: PDL_BASE_URL
      value: http://pdl-api.default/graphql
    - name: ORGANISASJON_RS_URL
      value: https://modapp-q1.adeo.no/ereg/api/v1/organisasjon
    - name: K9_FORMIDLING_DOKUMENTDATA_URL
      value: http://k9-formidling-dokumentdata.k9saksbehandling/k9/formidling/dokumentdata
    - name: K9_OPPDRAG_DIREKTE_URL
      value: http://k9-oppdrag.k9saksbehandling/k9/oppdrag/api
    - name: K9_TILBAKE_DIREKTE_URL
      value: http://k9-tilbake.k9saksbehandling/k9/tilbake/api
    - name: K9_FORMIDLING_URL
      value: http://k9-formidling.k9saksbehandling/k9/formidling
    - name : K9_PUNSJ_URL
      value: https://k9-punsj.dev.adeo.no/api
    - name: INFOTRYGD_BS_BASE_URI
      value: https://k9-infotrygd.dev.intern.nav.no
    - name: ARBEID_OG_INNTEKT_BASE_URL
      value: https://arbeid-og-inntekt.nais.preprod.local
    - name: K9_LOS_URL
      value: http://k9-los-api.k9saksbehandling/api

    # Restservice OMS spesifikt
    - name: K9_OMS_AARSKVANTUM_URL
      value: http://k9-aarskvantum.default
    - name: K9_OMS_UTVIDETRETT_URL
      value: https://omsorgsdager.dev.intern.nav.no/api

    # Restservice PSB spesifikt
    - name: K9_PSB_UTTAK_URL
      value: http://pleiepenger-barn-uttak.k9saksbehandling/pleiepenger-barn-uttak

    # Graphql services
    - name: SAF_BASE_URL
      value: http://saf-q1.teamdokumenthandtering

    # Sikkerhet:
    - name: OIDC_STS_HOST_URL
      value: https://security-token-service.nais.preprod.local
    - name: OIDC_OPENAM_HOST_URL
      value: https://isso-q.adeo.no/isso/oauth2
    - name: OIDC_OPENAM_CLIENT_ID
      value: k9-sak-q1

    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: ABAC_ATTRIBUTT_DRIFT
      value: "no.nav.abac.attributter.k9.drift"

    - name: SENSU_HOST
      value: "sensu.nais"
    - name: SENSU_PORT
      value: "3030"

    # Feature-flag
    - name: PSB_OPPG_OPPTJENING_PRIORITERING
      value: "true"
    - name: AUTOMATISK_VEDTAK_OMP_SOKNAD
      value: "true"
    - name: FRISINN_FLERE_SOKNADER_SAMME_DAG
      value: "true"
    - name: TOTRINN_TEMP_DEAKTIVERT
      value: "true"
    - name: K9TILBAKE_AKTIVERT
      value: "true"
    - name: ENABLE_STONADSTATISTIKK
      value: "true"
    - name: MAP_ALLE_KRAV
      value: "true"
    - name: ENABLE_BRUKERDIALOGINNSYN
      value: "true"
    - name: DISABLE_VURDER_TILBAKETREKK
      value: "true"
    - name: PSB_INFOTRYGD_MIGRERING
      value: "true"
    - name: FORLENGELSE_MEDLEMSKAP_ENABLET
      value: "true"
    - name: PSB_UTVIDE_VED_DODSFALL
      value: "true"
    - name: OMP_VERIFISERING_TILKJENT_YTELSE
      value: "true"
    - name: PSB_TREKKE_MIGRERT_PERIODE
      value: "true"
    - name: ENABLE_DOKUMENTMOTTAK_PPN
      value: "true"
    - name: KOMPLETTHET_MARKER_FRAVAER
      value: "true"

    # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-sak"

    - name: PIP_USERS
      value: "srvPDP,srvk9-tilbake,srvsaf,Z993210,Z994080"

    # Pleiepenger infotrygd migrering
    - name: INFOTRYGD_MIGRERING_TILLATELSER
      value: "Z990404,Z990422,Z994004,Z994337,Z994185"


    # FRISINN NYE REGLER 2022
    - name: FRISINN_NYTT_STP_TOGGLE
      value: "false"
