name: Openapi Generering
on:
  pull_request:
jobs:
  # Genererer ny openapi.json fil ut fr√• PR branch sin java kode.
  # Viss generert fil inneholder endringer i forhold til branch versjonen blir ny fil committa til PR branch.
  generate-openapi:
    name: Generer openapi.json
    permissions:
      contents: write
    uses: navikt/sif-gha-workflows/.github/workflows/openapi-generate.yml@openapi-next
    with:
      openapiFilePath: web/src/main/resources/openapi-ts-client/ung-sak.openapi.json
    secrets: inherit
